### ISSUE TITLE
Panic when implicitly referring method tyarg

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#494]
## Given
```
class A   
  def self.foo<S>(s: S)                                             
    p Pair.new(s, s)   # == Pair<S, S>.new(s, s)
  end                                                               
end                                                                 
A.foo(3)
```
## Expected
prints pair of 3 and 3
## Actual
>  thread 'main' panicked at 'unexpected', lib/shiika_core/src/ty/term_ty.rs:158:18
## Notes
We need to fix #493 before working on this.

**Comment by yhara** [comment]
Got another error:
```
thread 'main' panicked at lib/shiika_core/src/ty/term_ty.rs:165:17:
assertion failed: !typaram_ref.as_class
```
